name: release

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: erlef/setup-beam@v1.18.2
        with:
          otp-version: "27.0"
          rebar3-version: "3"
          gleam-version: "1.11.1"

      - run: |
          version="v$(cat gleam.toml | grep -m 1 "version" | sed -r "s/version *= *\"([[:digit:].]+)\"/\1/")"
          if [ "$version" != "${{ github.ref_name }}" ]; then
            echo "tag '${{ github.ref_name }}' does not match the version in gleam.toml"
            echo "expected a tag name 'v$version'"
            exit 1
          fi

        name: check version

      - run: gleam format --check

      - run: gleam publish -y
        env:
          HEXPM_API_KEY: ${{ secrets.HEXPM_API_KEY }}

      - uses: softprops/action-gh-release@v2
